name: Sync Salmon Directory
description: Syncs a directory to a Google Cloud bucket using rclone.
author: 'deephaven'
inputs:
  source:
    required: true
    type: string
    description: 'The source directory to sync.'
  destination:
    required: true
    type: string
    description: 'The destination directory to sync. Relative to the bucket.'
  project_number:
    required: true
    type: string
    description: 'The Google Cloud project number.'
  credentials:
    required: true
    type: string
    description: 'The Google Cloud credentials.'

runs:
  using: "composite"
  steps:
    - name: Setup rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone-version: v1.68.1

    - name: Decode credentials
      shell: bash
      run: |
        echo $RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS_ENCODED | base64 -d > $HOME/credentials.json
      env:
        RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS_ENCODED: ${{ inputs.credentials }}
      

    - name: Sync source to destination
      shell: bash
      env:
        RCLONE_CONFIG_GCS_TYPE: "google cloud storage"
        RCLONE_GCS_SERVICE_ACCOUNT_FILE: $HOME/credentials.json
        RCLONE_GCS_PROJECT_NUMBER: ${{ inputs.project_number }}
        RCLONE_GCS_BUCKET_POLICY_ONLY: "true"
      run: rclone sync ${{ inputs.source }} docs:${{ vars.DOCS_GOOGLE_CLOUD_BUCKET }}/${{ inputs.destination }}